---
# The purpose of this workflow is to automate the semantic-release of this software
# since this project uses gitmoji commits we can use the following plugin as part of
# to release software with https://github.com/semantic-release/semantic-release

name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup deps
        run: npm install semantic-release-gitmoji
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches=main